tables:
  2021-pinoli:
    file: "2021-pinoli.json"
    format: "JSON"
  2022-people:
    file: "2022-people.json"
    format: "JSON"
  relations:
    file: "relations.json"
    format: "JSON"
  2021-labs:
    file: "2021-labs.json"
    format: "JSON"
